// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Game, GameTableId } from "./tables/Game.sol";
import { GameMap, GameMapTableId } from "./tables/GameMap.sol";
import { Player, PlayerTableId } from "./tables/Player.sol";
