// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter, CounterTableId } from "./tables/Counter.sol";
import { Game, GameData, GameTableId } from "./tables/Game.sol";
import { GameState, GameStateTableId } from "./tables/GameState.sol";
import { GameMap, GameMapData, GameMapTableId } from "./tables/GameMap.sol";
import { MapItem, MapItemData, MapItemTableId } from "./tables/MapItem.sol";
import { MapItemValue, MapItemValueTableId } from "./tables/MapItemValue.sol";
import { IsPlayer, IsPlayerTableId } from "./tables/IsPlayer.sol";
import { Player, PlayerData, PlayerTableId } from "./tables/Player.sol";
import { RaiseColddown, RaiseColddownData, RaiseColddownTableId } from "./tables/RaiseColddown.sol";
import { AssetsList, AssetsListData, AssetsListTableId } from "./tables/AssetsList.sol";
import { Log, LogData, LogTableId } from "./tables/Log.sol";
import { TransactionList, TransactionListData, TransactionListTableId } from "./tables/TransactionList.sol";
