// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */
enum GameState {
  NotInited,
  InGame,
  Waiting
}

enum PlayerState {
  NotInited,
  InLobby,
  InGame
}
