// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IAssetsSystem {
  function pickFund() external;

  function pickAsset(uint8 assetKind) external;
}
