// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IAssetsSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IAssetsSystem {
  function pickFund() external;

  function pickAsset(uint8 assetKind) external;
}
