// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ILobbySystem {
  function joinGame() external returns (uint32);

  function askStart() external returns (uint32);

  function bytesToUintArray(bytes memory data) external pure returns (uint[][] memory);

  function convertArray(uint[8][8] memory fixedArray) external pure returns (uint[][] memory);
}
