// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ILobbySystem {
  function joinGame() external returns (uint32);

  function askStart() external returns (uint32);
}
