// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IMapSystem {
  function move(uint256 targetX, uint256 targetY) external returns (bool);
}
