// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITradeSystem {
  function trade(bytes32 targetPlayer, uint8 assetKind, uint32 money) external;
}
