// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

/**
 * @title ITradeSystem
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ITradeSystem {
  function trade(bytes32 targetPlayer, uint8 assetKind, uint32 money) external;

  function acceptTrade() external returns (bool);

  function rejectTrade() external returns (bool);

  function concatenate(string memory str, uint256 num) external pure returns (string memory);
}
