// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/codegen/interfaces/IBaseWorld.sol";

import { IAssetsSystem } from "./IAssetsSystem.sol";
import { IGameFlowSystem } from "./IGameFlowSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { ILobbySystem } from "./ILobbySystem.sol";
import { IMapSystem } from "./IMapSystem.sol";
import { ITradeSystem } from "./ITradeSystem.sol";

/**
 * @title IWorld
 * @notice This interface integrates all systems and associated function selectors
 * that are dynamically registered in the World during deployment.
 * @dev This is an autogenerated file; do not edit manually.
 */
interface IWorld is
  IBaseWorld,
  IAssetsSystem,
  IGameFlowSystem,
  IIncrementSystem,
  ILobbySystem,
  IMapSystem,
  ITradeSystem
{

}
