// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { IBaseWorld } from "@latticexyz/world/src/interfaces/IBaseWorld.sol";

import { IAssetsSystem } from "./IAssetsSystem.sol";
import { IIncrementSystem } from "./IIncrementSystem.sol";
import { ILobbySystem } from "./ILobbySystem.sol";
import { IMapSystem } from "./IMapSystem.sol";
import { ITradeSystem } from "./ITradeSystem.sol";

/**
 * The IWorld interface includes all systems dynamically added to the World
 * during the deploy process.
 */
interface IWorld is IBaseWorld, IAssetsSystem, IIncrementSystem, ILobbySystem, IMapSystem, ITradeSystem {

}
